[build]
    functions = "functions"

[[redirects]]
    from = "http://localhost:3000"
    to = "https://www.waldom.com/api/v1/:partNumber"
    status = 200
    force = true
    headers = {X-From = "Netlify"}
    [[headers]]
    for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
